version: "3.0"

services:
  user-details-service:
    build: .
    image: user-details-service:latest
    networks:
      - user-details
    ports:
      - ${APPLICATION_PORT}:8080

networks:
  user-details:
    driver: bridge