version: "3.0"

services:
  user-details-service:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    image: user-details-service:latest
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - user-details
    ports:
      - ${APPLICATION_PORT}:8080

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - user-details
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  pgdata:
    driver: local

networks:
  user-details:
    driver: bridge