spring:
  application:
    name: user-details-service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123

  sql:
    init:
      mode: always
      #      schema-locations: classpath:/data.sql
      continue-on-error: true

  liquibase:
    enabled: false